# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.13.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G49iiMBi6cvVQijTDZjAi7b7d9-DIa7F
"""

#Cau hoi trac nghiem - Cau hoi 12
def my_function(y):
    var = 1
    while (y > 1):
        # Your code here
        var = var * y
        y = y - 1
    return var

assert my_function(8) == 40320
print(my_function(4))

# Đáp án là c) 24