# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.7.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rag9MB4tdGbcLN54ROGm1pZOazpTgZ-N
"""

#Cau hoi trac nghiem - Cau hoi 7
def my_function(x, y):
    # Your code here
    # su dung extend de noi y vao x
    x.extend(y)
    return x

list_num1 = ['a', 2, 5]
list_num2 = [1, 1]
list_num3 = [0, 0]

assert my_function(list_num1, my_function(list_num2, list_num3)) == ['a', 2, 5, 1, 1, 0, 0]

list_num1 = [1 , 2]
list_num2 = [3 , 4]
list_num3 = [0 , 0]

print(my_function(list_num1, my_function(list_num2, list_num3)))

# Đáp án là a) True