# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.15.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14G4i3LHHHBirPmpgIoVY1ZSYI4F8-9uH
"""

#Cau hoi trac nghiem - Cau hoi 15
def function_helper(x):
    # Your code here
    # Neu x >0 tra ve ’T ’, nguoc lai tra ve ’N’
    if x > 0:
        return 'T'
    else:
        return 'N'

def my_function(data):
    res = [function_helper(x) for x in data]
    return res

data = [10, 0, -10, -1]
assert my_function(data) == ['T', 'N', 'N', 'N']

data = [2 , 3 , 5 , -1]
print (my_function(data))

# Đáp án là b) tocirpa