# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.6.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pr2UuGbn9vc_AjLCv0BECTLDuCTiyrE7
"""

#Cau hoi trac nghiem - Cau hoi 6
def my_function (data, max, min) :
    result = []
    for i in data:
    # Your code here
      # Neu i < min thi them min vao result
      if i < min:
          result.append(min)
      elif i > max:
          result.append(max)
      else :
          result.append(i)
    return result

my_list = [5, 2, 5, 0, 1]
max = 1
min = 0
assert my_function(max = max, min = min, data = my_list) == [1, 1, 1, 0, 1]
my_list = [10, 2, 5, 0, 1]
max = 2
min = 1
print (my_function(max = max, min = min, data = my_list))

# Đáp án là c) [2, 2, 2, 1, 1]