# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.16.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oNI1yzLcEiv2__ce9EcgY5hAe1Xr6o9R
"""

#Cau hoi trac nghiem - Cau hoi 16
def function_helper(x, data):
    for i in data:
    # Your code here
    # Neu x == i thi return 0
        if x==i:
            return 0
    return 1

def my_function(data):
    res = []
    for i in data:
        if function_helper(i, res):
            res.append(i)
    return res

lst = [10, 10, 9, 7, 7]
assert my_function(lst) ==[10, 9, 7]

lst = [9, 9, 8, 1, 1]
print(my_function(lst))

# Đáp án là a) [9, 8, 1]