# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.11.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmeRt8mzzjo304lyvzWk6EjKBxYLpt1_
"""

#Cau hoi trac nghiem - Cau hoi 11
def my_function(list_nums = [0, 1, 2]):
    var = 0
    for i in list_nums:
        var += i
    # Your code here : Tra ve gia tri trung binh cua list bang cach chia var cho so luong phan tu trong list_mums
    return var/len(list_nums) if len(list_nums)> 0 else 0

assert my_function([4, 6, 8]) == 6
print(my_function())

# Đáp án là a) 1.0