# -*- coding: utf-8 -*-
"""ExerciseM1W2_I.3.CountWords.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_JaEroF7nGhzG8Ak_jK85YFzOB1Dl36
"""

# define function to read a file
def read_file (file_name):
    with open(file_name,'r') as file:
        data = file.read()
        file.close()
    return data.split('\n')

# define function to cout words in lower case
def count_words(file_name):
    dictionary_words = {}
    data = read_file(file_name)
    for line in data:
        for word in line.split(' '):
            # print(word.lower())
            if dictionary_words.get(word.lower()) is None:
                dictionary_words[word.lower()] = 1
            else:
                dictionary_words[word.lower()] += 1
    dictionary_words = dict(sorted(dictionary_words.items()))
    return dictionary_words

# test function count_chars (string)
! gdown https://drive.google.com/uc?id=1IBScGdW2xlNsc9v5zSAya548kNgiOrko
file_path = '/content/P1_data.txt'
count_words(file_path)