# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.8.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Em-F4qWUPZmO3epcKWqDza6um1ykk1rx
"""

#Cau hoi trac nghiem - Cau hoi 7
def my_function(n):
    # Your code here
    return min(n)

my_list = [1, 22, 93, -100]
assert my_function(my_list) == -100

my_list = [1 , 2 , 3 , -1]
print (my_function(my_list))

# Đáp án là c) -1