# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.1.max_kernel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZcwK0HC87vcQJyyCJblpyLKQzTo0qfcn
"""

#Cau hoi trac nghiem - Cau hoi 1
def max_kernel (num_list,k):
    result = []

    # Your Code Here
    if k > len(num_list):
        print(f"k = {k} lớn hơn độ dài của danh sách len = {len(num_list)} nên không thực hiện được.")
        return
    if k < 1:
        print("k phải >= 1.")
        return
    for i in range(len(num_list) - k + 1):
        result = result + [max(num_list[i:i+k])]
    # End Code Here

    return result

assert max_kernel ([3 , 4 , 5 , 1 , -44] , 3) == [5 , 5 , 5]
num_list = [3 , 4 , 5 , 1 , -44 , 5 ,10 , 12 ,33 , 1]
k = 3
print ( max_kernel ( num_list , k ) )

# Đáp án là a) [5, 5, 5, 5, 10, 12, 33, 33]