# -*- coding: utf-8 -*-
"""ExerciseM1W2_I.2.CountChars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0xK8TDonfeyKQ5UT47clFEiFGK28VGb
"""

# define function count_chars (string)


def count_chars(string):
    # đổi kiểu string --> list
    string_list = list(string)
    # sắp xếp list
    string_list.sort()

    dictionary_chars = {}
    for char in string_list:
        if dictionary_chars.get(char) is None:
            dictionary_chars[char] = 1
        else:
            dictionary_chars[char] += 1

    print(dictionary_chars)


# test function count_chars (string)
string = "jgdlgjdfglkdfjg kgjdgdfjg ldjgtu3"
count_chars(string)
