# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.12.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoF-W3qGA9aI-Stfw99yv7Ub3PeiMT8V
"""

#Cau hoi trac nghiem - Cau hoi 12
def my_function(data):
    var = []
    for i in data :
    # Your code here
    # Neu i chia het cho 3 thi them i vao list var
        if i%3 == 0:
            var.append(i)
    return var

assert my_function([3, 9, 4, 5]) == [3, 9]
print (my_function ([1, 2, 3, 5, 6]))

# Đáp án là a) 1.0