# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.5.check_the_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifgtUjSlb6GD1Avg_GWsf78GvMt98VbJ
"""

#Cau hoi trac nghiem - Cau hoi 5
def check_the_number(N):
    list_of_numbers = []
    result = ""
    for i in range (1, 5) :
    # Your code here
    #Su dung append them i vao trong list_of_number
        list_of_numbers.append(i)
    if N in list_of_numbers :
        results = "True"
    if N not in list_of_numbers :
        results = "False"
    return results

N = 7
assert check_the_number(N) == "False"
N = 2
results = check_the_number(N)
print(results)

# Đáp án là a) True