# -*- coding: utf-8 -*-
"""ExerciseM1W2_II.14.my_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCjwohXerH2knJKrltmlYh40pToRxeVt
"""

#Cau hoi trac nghiem - Cau hoi 14
def my_function(x):
    # your code here
    return x[::-1]

x = 'I can do it'
assert my_function(x) == "ti od nac I"

x = 'apricot'
print(my_function(x))

# Đáp án là b) tocirpa