# -*- coding: utf-8 -*-
"""M02_W1_Exercise3_Analyze_Data_Table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CtmsG2ALXnQBsoXfqdrvNPMVCHbG3h2

# Download data table from csv file
"""

# Download data
#!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')
#print(df)
data = df.to_numpy()
#print(data)

"""# Question 15"""

import numpy as np

sales_data = data[:,3]
max_sales = np.max(sales_data)
max_sales_index = np.argmax(sales_data)

print("Max:", max_sales, "- Index:", max_sales_index)

"""# Question 16"""

import numpy as np

tv_data = data[:,0]
avg_tv = np.mean(tv_data)

print(avg_tv)

"""# Question 17"""

import numpy as np

sales_data = data[:,3]
sales_greater_20 = np.sum(sales_data>=20)

print(sales_greater_20)

"""# Question 18"""

import numpy as np

sales_filter = data[:,3]>=15
radio_data = data[:,1]
radio_filter = radio_data * sales_filter
avg_radio = np.sum(radio_filter)/np.sum(sales_filter)
print(avg_radio)

"""# Question 19"""

import numpy as np

newspaper_data = data[:,2]
avg_newspaper = np.mean(newspaper_data)
newspaper_filter = newspaper_data > avg_newspaper
sales_data = data[:,3]
sales_filter = sales_data * newspaper_filter
sum_sales = np.sum(sales_filter)
print(sum_sales)

"""# Question 20"""

import numpy as np

sales_data = data[:,3]
sales_avg = np.mean(sales_data)
scores = np.where(sales_data == sales_avg, 'Average',
                  np.where(sales_data > sales_avg, 'Good', 'Bad'))

print(scores[7:10])

"""# Question 21"""

import numpy as np

sales_data = data[:,3]
sales_avg = np.mean(sales_data)
sales_avg_closet = np.min(abs(sales_data - sales_avg)) + sales_avg

scores = np.where(sales_data == sales_avg_closet, 'Average',
                  np.where(sales_data > sales_avg_closet, 'Good', 'Bad'))

print(sales_avg)
print(sales_avg_closet)
print(scores[7:10])